apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/kc8421/argocd-15-min.git
    targetRevision: HEAD
  destination:
    namespace: sandbox
    server: https://aks-test1-dns-3693c5bf.hcp.westeurope.azmk8s.io:443
  syncPolicy:
    automated:
      selfHeal: true
      prune: true