apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-toolkit.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: devopstoolkit.argocdtest
      version: v3
  destination:
    namespace: sandbox
    server: https://aks-test1-dns-3693c5bf.hcp.westeurope.azmk8s.io:443
  syncPolicy:
    automated:
      selfHeal: true
      prune: true